
package mypackage;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProductService", targetNamespace = "http://Product.biniek.daniel/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProductService {


    /**
     * 
     * @return
     *     returns mypackage.OrderType
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Product.biniek.daniel/ProductService/getProductsRequest", output = "http://Product.biniek.daniel/ProductService/getProductsResponse")
    public OrderType getProducts();

    /**
     * 
     * @param arg0
     * @return
     *     returns mypackage.OrderType
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Product.biniek.daniel/ProductService/createOrderRequest", output = "http://Product.biniek.daniel/ProductService/createOrderResponse")
    public OrderType createOrder(
        @WebParam(name = "arg0", partName = "arg0")
        OrderType arg0);

}
