
package mypackage;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ProductServiceImpl", targetNamespace = "http://Product.biniek.daniel", wsdlLocation = "file:/E:/systemy rozproszone/MiddleTier/Product/src/main/java/daniel/biniek/Product/ProductServiceImpl.wsdl")
public class ProductServiceImpl
    extends Service
{

    private final static URL PRODUCTSERVICEIMPL_WSDL_LOCATION;
    private final static WebServiceException PRODUCTSERVICEIMPL_EXCEPTION;
    private final static QName PRODUCTSERVICEIMPL_QNAME = new QName("http://Product.biniek.daniel", "ProductServiceImpl");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/E:/systemy rozproszone/MiddleTier/Product/src/main/java/daniel/biniek/Product/ProductServiceImpl.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PRODUCTSERVICEIMPL_WSDL_LOCATION = url;
        PRODUCTSERVICEIMPL_EXCEPTION = e;
    }

    public ProductServiceImpl() {
        super(__getWsdlLocation(), PRODUCTSERVICEIMPL_QNAME);
    }

    public ProductServiceImpl(WebServiceFeature... features) {
        super(__getWsdlLocation(), PRODUCTSERVICEIMPL_QNAME, features);
    }

    public ProductServiceImpl(URL wsdlLocation) {
        super(wsdlLocation, PRODUCTSERVICEIMPL_QNAME);
    }

    public ProductServiceImpl(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PRODUCTSERVICEIMPL_QNAME, features);
    }

    public ProductServiceImpl(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProductServiceImpl(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProductService
     */
    @WebEndpoint(name = "ProductServiceImpl")
    public ProductService getProductServiceImpl() {
        return super.getPort(new QName("http://Product.biniek.daniel", "ProductServiceImpl"), ProductService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProductService
     */
    @WebEndpoint(name = "ProductServiceImpl")
    public ProductService getProductServiceImpl(WebServiceFeature... features) {
        return super.getPort(new QName("http://Product.biniek.daniel", "ProductServiceImpl"), ProductService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PRODUCTSERVICEIMPL_EXCEPTION!= null) {
            throw PRODUCTSERVICEIMPL_EXCEPTION;
        }
        return PRODUCTSERVICEIMPL_WSDL_LOCATION;
    }

}
